#!/usr/bin/env sh
# This file was created by pub v3.2.6.
# Package: flutterfire_cli
# Version: 1.0.0
# Executable: flutterfire
# Script: flutterfire
if [ -f /home/pranav/.pub-cache/global_packages/flutterfire_cli/bin/flutterfire.dart-3.2.6.snapshot ]; then
  dart "/home/pranav/.pub-cache/global_packages/flutterfire_cli/bin/flutterfire.dart-3.2.6.snapshot" "$@"
  # The VM exits with code 253 if the snapshot version is out-of-date.
  # If it is, we need to delete it and run "pub global" manually.
  exit_code=$?
  if [ $exit_code != 253 ]; then
    exit $exit_code
  fi
  dart pub global run flutterfire_cli:flutterfire "$@"
else
  dart pub global run flutterfire_cli:flutterfire "$@"
fi
